site_name: Laboratorios Integrasoft
site_description: Documentación y Guías de Laboratorios
site_author: Tu Nombre

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

# Plugins and Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true

nav:
  - Inicio: index.md
  - Laboratorios:
    - BDD .NET Core: lab_bdd_netcore_codespaces.md
